### ISSUE TITLE
Probability Learning Tracking 

### ISSUE THREAD

**Issue by Abigail6on** [Abigail6on/Python-Data-Science-Handbook-notebook#1]
Current Learning pattern:

- [x] L15.8 Trajectory Estimation Illustration

- [x] L16.1 Lecture Overview

- [x] L16.2 LMS Estimation in the Absence of Observations

- [x] L16.3 LMS Estimation of One Random Variable Based on Another

- [x] L16.4 LMS Performance Evaluation

- [x] L16.5 Example: The LMS Estimate

- [x] L16.6 Example Continued: LMS Performance Evaluation

- [x] L16.7 LMS Estimation with Multiple Observations or Unknowns

- [x] L16.8 Properties of the LMS Estimation Error

- [x] L17.1 Lecture Overview

- [x] L17.2 LLMS Formulation

- [x] L17.3 Solution to the LLMS Problem

- [x] L17.4 Remarks on the LLMS Solution and on the Error Variance

- [x] L17.5 LLMS Example
